#!/usr/bin/env python3
"""Generate the leaderboard.md trophy wall from profile.json."""

import json
from datetime import datetime
from pathlib import Path

SKILL_DIR = Path.home() / ".skill-issue"


def progress_bar(fraction: float, width: int = 20) -> str:
    filled = round(fraction * width)
    return "█" * filled + "░" * (width - filled)


def level_icon(level: str) -> str:
    return {"Master": "⭐", "Expert": "🔷", "Practitioner": "🔶", "Apprentice": "⬜"}.get(level, "⬜")


def generate():
    with open(SKILL_DIR / "profile.json") as f:
        p = json.load(f)

    total = p["total_challenges"]
    correct = p["scores"].get("2", 0) + p["scores"].get("3", 0)
    accuracy = (correct / total * 100) if total > 0 else 0

    next_level_map = {
        "Apprentice": ("Practitioner", 500),
        "Practitioner": ("Expert", 2000),
        "Expert": ("Master", 5000),
        "Master": (None, None),
    }
    next_name, next_xp = next_level_map[p["overall_level"]]
    if next_xp:
        level_str = f"{p['overall_level']} ({p['total_xp']} / {next_xp} XP to {next_name})"
    else:
        level_str = f"{p['overall_level']} ({p['total_xp']} XP — MAX)"

    lines = [
        "# 🧠 skill-issue — Human Performance Dashboard\n",
        f"**Player**: {p['username']}",
        f"**Level**: {level_str}",
        f"**Streak**: 🔥 {p['current_streak']} (Best: {p['best_streak']})",
        f"**Accuracy**: {accuracy:.0f}% ({correct}/{total} correct)\n",
        "---\n",
        "## Skill Radar\n",
        "| Topic | Level | Accuracy | Attempts | Progress |",
        "|:------|:------|:---------|:---------|:---------|",
    ]

    for topic, data in sorted(p["topics"].items(), key=lambda x: -x[1]["attempts"]):
        recent = data["scores"][-20:]
        acc = sum(1 for s in recent if s >= 2) / len(recent) * 100 if recent else 0
        icon = level_icon(data["level"])
        bar = progress_bar(acc / 100)
        lines.append(f"| {topic} | {icon} {data['level']} | {acc:.0f}% | {data['attempts']} | {bar} |")

    if p["milestones"]:
        lines.append("\n## Milestones Unlocked 🏆\n")
        milestone_labels = {
            "first_challenge": "🎯 First Challenge",
            "streak_5": "🔥 5-Streak",
            "streak_10": "🔥 10-Streak",
            "streak_20": "🔥 20-Streak",
            "topic_expert": "🔷 Expert",
            "topic_master": "⭐ Master",
            "xp_500": "💎 500 XP",
            "xp_2000": "💎 2000 XP",
            "xp_5000": "💎 5000 XP",
            "all_types": "🌈 All Challenge Types",
            "comeback": "💪 Comeback",
        }
        for m in p["milestones"]:
            date = m["date"][:10]
            base = milestone_labels.get(m["type"], m["type"])
            topic_suffix = f": {m['topic']}" if "topic" in m else ""
            lines.append(f"- {base}{topic_suffix} — {date}")

    session_dir = SKILL_DIR / "sessions"
    session_files = sorted(session_dir.glob("*.json"), reverse=True)[:10]
    if session_files:
        lines.append("\n## Recent Sessions\n")
        lines.append("| Date | Challenges | Correct | XP Earned | Topics |")
        lines.append("|:-----|:-----------|:--------|:----------|:-------|")
        for sf in session_files:
            with open(sf) as f:
                s = json.load(f)
            summary = s.get("summary", {})
            date = s.get("started_at", "")[:10]
            total_c = summary.get("total_challenges", 0)
            correct_c = summary.get("scores", {}).get("2", 0) + summary.get("scores", {}).get("3", 0)
            xp = summary.get("xp_earned", 0)
            topics = ", ".join(summary.get("topics_covered", [])[:3])
            lines.append(f"| {date} | {total_c} | {correct_c} | +{xp} | {topics} |")

    lines.append("\n---")
    lines.append(f"*Generated by skill-issue v1.0 | Last updated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC*")

    report = "\n".join(lines)
    with open(SKILL_DIR / "leaderboard.md", "w") as f:
        f.write(report)
    print(report)


if __name__ == "__main__":
    generate()
